version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8099:8099"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs
    networks:
      - app-network

  nodejs:
    build: .
    command: npm run start:prod
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge